"""Version tracking, amendment management, audit log, and diff engine.

Data model (JSON file storage for Phase 1):

protocol_{id}.json  — main protocol record (unchanged from before)
versions_{id}.json  — version history for a protocol
amendments_{id}.json — amendments branched from a protocol
audit_{id}.json     — audit log entries

Version lifecycle:
  v0.1 (Draft, auto-generated by Ada)
  v0.2 (SD Review, Study Director edits)
  v0.3 (Sponsor Review, imported external edits)
  v1.0 (Finalized, signed off)

Amendment lifecycle:
  Amendment 1 → v0.1 ... v1.0 (finalized)
  Amendment 2 → v0.1 ... v1.0 (finalized)
  Each amendment is a branched copy with its own version history.
"""

import json
import copy
import time
import hashlib
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from app.core.config import settings
from app.services.storage import get_storage_backend

import logging
logger = logging.getLogger(__name__)


# ============================================================================
# STORAGE ACCESS (delegates to configured backend)
# ============================================================================

def _load_versions(protocol_id: str) -> List[dict]:
    return get_storage_backend().load_versions(protocol_id)

def _save_versions(protocol_id: str, versions: list):
    get_storage_backend().save_versions(protocol_id, versions)


def create_version(
    protocol_id: str,
    extracted_json: dict,
    author: str = "Ada (auto-generated)",
    label: str = "",
    status: str = "Draft",
    version_override: str = None,
) -> dict:
    """Create a new version snapshot of the protocol's extracted JSON.

    Returns the new version record.
    """
    versions = _load_versions(protocol_id)

    # Determine version number
    if version_override:
        version_num = version_override
    elif not versions:
        version_num = "v0.1"
    else:
        last = versions[-1]["version"]
        # Parse last version
        major, minor = _parse_version(last)
        if status.lower() in ("finalized", "ready for signature", "signed"):
            version_num = f"v{major + 1}.0"
        else:
            version_num = f"v{major}.{minor + 1}"

    # Compute content hash to detect actual changes
    content_hash = _hash_json(extracted_json)

    # Check if identical to last version (skip duplicate snapshots)
    if versions and versions[-1].get("content_hash") == content_hash:
        logger.info(f"Skipping duplicate version for {protocol_id} (content unchanged)")
        return versions[-1]

    version_record = {
        "version": version_num,
        "protocol_id": protocol_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "author": author,
        "label": label or f"Version {version_num}",
        "status": status,
        "content_hash": content_hash,
        "extracted_json": extracted_json,
        "field_count": _count_nonempty_fields(extracted_json),
    }

    versions.append(version_record)
    _save_versions(protocol_id, versions)

    # Log audit entry
    add_audit_entry(
        protocol_id=protocol_id,
        action="version_created",
        author=author,
        details={"version": version_num, "status": status, "field_count": version_record["field_count"]},
    )

    logger.info(f"Created version {version_num} for protocol {protocol_id} by {author}")
    return version_record


def get_versions(protocol_id: str) -> List[dict]:
    """Get all versions for a protocol (without full JSON to keep response small)."""
    versions = _load_versions(protocol_id)
    # Return summaries (exclude full extracted_json for list view)
    summaries = []
    for v in versions:
        summaries.append({
            "version": v["version"],
            "timestamp": v["timestamp"],
            "author": v["author"],
            "label": v["label"],
            "status": v["status"],
            "field_count": v.get("field_count", 0),
            "content_hash": v.get("content_hash", ""),
        })
    return summaries


def get_version_detail(protocol_id: str, version_num: str) -> Optional[dict]:
    """Get a specific version with full extracted JSON."""
    versions = _load_versions(protocol_id)
    for v in versions:
        if v["version"] == version_num:
            return v
    return None


def update_version_status(protocol_id: str, version_num: str, new_status: str, author: str = "System") -> Optional[dict]:
    """Update the status of a specific version."""
    versions = _load_versions(protocol_id)
    for v in versions:
        if v["version"] == version_num:
            old_status = v["status"]
            v["status"] = new_status
            _save_versions(protocol_id, versions)
            add_audit_entry(
                protocol_id=protocol_id,
                action="version_status_changed",
                author=author,
                details={"version": version_num, "old_status": old_status, "new_status": new_status},
            )
            return v
    return None


# ============================================================================
# AMENDMENT MANAGEMENT
# ============================================================================

def _load_amendments(protocol_id: str) -> List[dict]:
    return get_storage_backend().load_amendments(protocol_id)

def _save_amendments(protocol_id: str, amendments: list):
    get_storage_backend().save_amendments(protocol_id, amendments)


def create_amendment(
    protocol_id: str,
    base_version: str = None,
    author: str = "Study Director",
    reason: str = "",
) -> dict:
    """Create a new amendment branched from a protocol version.

    An amendment gets its own version history (v0.1, v0.2... until finalized).
    Returns the amendment record.
    """
    amendments = _load_amendments(protocol_id)

    # Determine amendment number
    amendment_num = len(amendments) + 1
    amendment_id = f"{protocol_id}-amend-{amendment_num}"

    # Get the base version's extracted JSON
    if base_version:
        base = get_version_detail(protocol_id, base_version)
    else:
        # Use the latest version
        versions = _load_versions(protocol_id)
        base = versions[-1] if versions else None

    if not base:
        raise ValueError(f"No base version found for protocol {protocol_id}")

    base_json = copy.deepcopy(base.get("extracted_json", {}))

    amendment_record = {
        "amendment_id": amendment_id,
        "amendment_number": amendment_num,
        "protocol_id": protocol_id,
        "base_version": base.get("version", "v0.1"),
        "created_at": datetime.utcnow().isoformat() + "Z",
        "author": author,
        "reason": reason,
        "status": "In Progress",
        "current_version": "v0.1",
        "extracted_json": base_json,  # Starts as a copy of the base
        "changes_summary": [],  # Will be populated as edits are made
    }

    amendments.append(amendment_record)
    _save_amendments(protocol_id, amendments)

    # Also create a v0.1 in the amendment's own version history
    _save_versions(amendment_id, [{
        "version": "v0.1",
        "protocol_id": amendment_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "author": author,
        "label": f"Amendment {amendment_num} - Initial Draft",
        "status": "Draft",
        "content_hash": _hash_json(base_json),
        "extracted_json": base_json,
        "field_count": _count_nonempty_fields(base_json),
    }])

    add_audit_entry(
        protocol_id=protocol_id,
        action="amendment_created",
        author=author,
        details={
            "amendment_id": amendment_id,
            "amendment_number": amendment_num,
            "base_version": base.get("version", "v0.1"),
            "reason": reason,
        },
    )

    logger.info(f"Created Amendment {amendment_num} for protocol {protocol_id}")
    return amendment_record


def get_amendments(protocol_id: str) -> List[dict]:
    """Get all amendments for a protocol (summaries)."""
    amendments = _load_amendments(protocol_id)
    summaries = []
    for a in amendments:
        summaries.append({
            "amendment_id": a["amendment_id"],
            "amendment_number": a["amendment_number"],
            "base_version": a["base_version"],
            "created_at": a["created_at"],
            "author": a["author"],
            "reason": a.get("reason", ""),
            "status": a["status"],
            "current_version": a["current_version"],
            "changes_count": len(a.get("changes_summary", [])),
        })
    return summaries


def get_amendment_detail(protocol_id: str, amendment_number: int) -> Optional[dict]:
    """Get a specific amendment with full data."""
    amendments = _load_amendments(protocol_id)
    for a in amendments:
        if a["amendment_number"] == amendment_number:
            return a
    return None


def update_amendment(
    protocol_id: str,
    amendment_number: int,
    sections: dict,
    author: str = "Study Director",
) -> dict:
    """Update fields in an amendment's extracted JSON.

    Tracks each change in the changes_summary list.
    Returns the updated amendment.
    """
    amendments = _load_amendments(protocol_id)
    target = None
    for a in amendments:
        if a["amendment_number"] == amendment_number:
            target = a
            break

    if not target:
        raise ValueError(f"Amendment {amendment_number} not found for protocol {protocol_id}")

    extracted = target.get("extracted_json", {})
    changes_made = []

    for key, new_value in sections.items():
        parts = key.split(".")
        obj = extracted
        old_value = None

        # Navigate to parent
        for part in parts[:-1]:
            if isinstance(obj, dict) and part in obj:
                obj = obj[part]
            else:
                obj = None
                break

        if obj is not None and isinstance(obj, dict):
            field_name = parts[-1]
            old_value = obj.get(field_name)
            obj[field_name] = new_value

            if str(old_value) != str(new_value):
                changes_made.append({
                    "field": key,
                    "old_value": str(old_value) if old_value else "",
                    "new_value": str(new_value),
                    "timestamp": datetime.utcnow().isoformat() + "Z",
                    "author": author,
                })

    target["extracted_json"] = extracted
    target["changes_summary"].extend(changes_made)

    # Bump amendment version
    old_ver = target["current_version"]
    major, minor = _parse_version(old_ver)
    target["current_version"] = f"v{major}.{minor + 1}"

    _save_amendments(protocol_id, amendments)

    # Save a version snapshot for the amendment
    amendment_id = target["amendment_id"]
    create_version(
        protocol_id=amendment_id,
        extracted_json=extracted,
        author=author,
        label=f"Amendment {amendment_number} - {target['current_version']}",
        status="In Progress",
    )

    # Audit
    add_audit_entry(
        protocol_id=protocol_id,
        action="amendment_edited",
        author=author,
        details={
            "amendment_number": amendment_number,
            "fields_changed": len(changes_made),
            "version": target["current_version"],
        },
    )

    return {
        "amendment_number": amendment_number,
        "current_version": target["current_version"],
        "fields_changed": len(changes_made),
        "changes": changes_made,
    }


def finalize_amendment(
    protocol_id: str,
    amendment_number: int,
    author: str = "Study Director",
) -> dict:
    """Finalize an amendment: mark it finalized and merge into main version history."""
    amendments = _load_amendments(protocol_id)
    for a in amendments:
        if a["amendment_number"] == amendment_number:
            a["status"] = "Finalized"
            major, minor = _parse_version(a["current_version"])
            final_version = f"v{major + 1}.0"
            a["current_version"] = final_version
            _save_amendments(protocol_id, amendments)

            # Merge amendment data into main version history
            amended_json = a.get("extracted_json", {})
            if amended_json:
                create_version(
                    protocol_id=protocol_id,
                    extracted_json=amended_json,
                    author=author,
                    label=f"Amendment {amendment_number} finalized",
                    status="Approved",
                    version_override=final_version,
                )

                # Also update the main protocol data via storage backend
                storage = get_storage_backend()
                protocol = storage.load_protocol(protocol_id)
                if protocol:
                    protocol["extracted_json"] = amended_json
                    protocol["status"] = "amended"
                    storage.save_protocol(protocol_id, protocol)

            add_audit_entry(
                protocol_id=protocol_id,
                action="amendment_finalized",
                author=author,
                details={
                    "amendment_number": amendment_number,
                    "final_version": final_version,
                    "merged_to_main": True,
                },
            )
            return {"amendment_number": amendment_number, "status": "Finalized", "version": final_version}
    raise ValueError(f"Amendment {amendment_number} not found")


# ============================================================================
# DIFF ENGINE
# ============================================================================

# Section labels matching the protocol template structure
PROTOCOL_SECTIONS = [
    "BasicDetails", "StudyInfo", "Personnel", "RegulatoryCompliance",
    "QualityAssurance", "TestMaterial", "TestSystem", "Husbandry",
    "ExperimentalDesign", "ExperimentalObservationsandProcedures",
    "LaboratoryAssessments", "TerminalProceduresandPathology",
    "DataAnalysis", "ComputerizedSystemsAndAnalyzers", "AnimalCareCompliance",
    "Reporting", "ArchivalStorage", "TissueCollectionsandPreservation",
    "Approvals", "Schedule",
]

SECTION_DISPLAY_NAMES = {
    "BasicDetails": "Study Information",
    "StudyInfo": "Study Details",
    "Personnel": "Personnel",
    "RegulatoryCompliance": "Regulatory Compliance",
    "QualityAssurance": "Quality Assurance",
    "TestMaterial": "Test Material",
    "TestSystem": "Test System",
    "Husbandry": "Husbandry",
    "ExperimentalDesign": "Experimental Design",
    "ExperimentalObservationsandProcedures": "Clinical Observations & Procedures",
    "LaboratoryAssessments": "Laboratory Assessments",
    "TerminalProceduresandPathology": "Terminal Procedures and Pathology",
    "DataAnalysis": "Data Analysis",
    "ComputerizedSystemsAndAnalyzers": "Computerized Systems and Analyzers",
    "AnimalCareCompliance": "Animal Care Compliance",
    "Reporting": "Reporting",
    "ArchivalStorage": "Archival Storage",
    "TissueCollectionsandPreservation": "Tissue Collections and Preservation",
    "Approvals": "Approvals",
    "Schedule": "Schedule",
}


def compute_diff(original_json: dict, amended_json: dict) -> List[dict]:
    """Compute a section-by-section diff between two protocol JSONs.

    Returns a list of diff sections in the format expected by the frontend:
    {
        section: "Study Information",
        id: "study-info",
        type: "modified" | "unchanged" | "added" | "removed",
        severity: "substantive" | "minor" | "none",
        original: "summary of original values",
        amended: "summary of amended values",
        changes: ["list of specific changes"],
        impact: "downstream impact description",
        field_details: [{field, old, new}]
    }
    """
    diff_sections = []

    # Get all top-level keys from both
    all_keys = set(list(original_json.keys()) + list(amended_json.keys()))

    for section_key in PROTOCOL_SECTIONS:
        if section_key not in all_keys:
            continue

        orig_section = original_json.get(section_key, {})
        amend_section = amended_json.get(section_key, {})

        display_name = SECTION_DISPLAY_NAMES.get(section_key, section_key)
        section_id = section_key.lower().replace(" ", "-")

        # Flatten both sections for field-by-field comparison
        orig_flat = _flatten_for_diff(orig_section, section_key)
        amend_flat = _flatten_for_diff(amend_section, section_key)

        all_fields = set(list(orig_flat.keys()) + list(amend_flat.keys()))

        field_changes = []
        for field in sorted(all_fields):
            orig_val = str(orig_flat.get(field, "")).strip()
            amend_val = str(amend_flat.get(field, "")).strip()

            if orig_val != amend_val:
                # Skip empty-to-empty changes
                if not orig_val and not amend_val:
                    continue
                field_changes.append({
                    "field": field,
                    "original": orig_val,
                    "amended": amend_val,
                })

        if not field_changes:
            # Section unchanged
            orig_summary = _summarize_section(orig_section)
            diff_sections.append({
                "section": display_name,
                "id": section_id,
                "type": "unchanged",
                "severity": "none",
                "original": orig_summary,
                "amended": orig_summary,
                "changes": [],
                "impact": "",
                "costImpact": "",
                "field_details": [],
            })
        else:
            # Determine severity based on number and nature of changes
            severity = _classify_severity(section_key, field_changes)
            change_descriptions = _describe_changes(section_key, field_changes)
            impact = _assess_impact(section_key, field_changes)

            diff_sections.append({
                "section": display_name,
                "id": section_id,
                "type": "modified",
                "severity": severity,
                "original": _summarize_section(orig_section),
                "amended": _summarize_section(amend_section),
                "changes": change_descriptions,
                "impact": impact,
                "costImpact": "",  # Phase 2: cost estimation
                "field_details": field_changes,
            })

    # Also check for sections only in amended (added)
    for key in amended_json:
        if key not in original_json and key in SECTION_DISPLAY_NAMES:
            diff_sections.append({
                "section": SECTION_DISPLAY_NAMES.get(key, key),
                "id": key.lower(),
                "type": "added",
                "severity": "substantive",
                "original": "",
                "amended": _summarize_section(amended_json[key]),
                "changes": [f"New section added: {SECTION_DISPLAY_NAMES.get(key, key)}"],
                "impact": "New section requires full review.",
                "costImpact": "",
                "field_details": [],
            })

    return diff_sections


def compare_versions(protocol_id: str, version_a: str, version_b: str) -> dict:
    """Compare two versions of a protocol and return the diff report.

    Returns the full comparison data expected by the frontend's
    renderAmendmentReport() function.
    """
    va = get_version_detail(protocol_id, version_a)
    vb = get_version_detail(protocol_id, version_b)

    if not va:
        raise ValueError(f"Version {version_a} not found for protocol {protocol_id}")
    if not vb:
        raise ValueError(f"Version {version_b} not found for protocol {protocol_id}")

    diff_sections = compute_diff(va["extracted_json"], vb["extracted_json"])

    modified = [d for d in diff_sections if d["type"] == "modified"]
    substantive = [d for d in modified if d["severity"] == "substantive"]
    minor = [d for d in modified if d["severity"] == "minor"]
    unchanged = [d for d in diff_sections if d["type"] == "unchanged"]

    return {
        "protocol_id": protocol_id,
        "version_a": version_a,
        "version_b": version_b,
        "timestamp_a": va["timestamp"],
        "timestamp_b": vb["timestamp"],
        "summary": {
            "total_sections": len(diff_sections),
            "modified_count": len(modified),
            "substantive_count": len(substantive),
            "minor_count": len(minor),
            "unchanged_count": len(unchanged),
        },
        "diff_sections": diff_sections,
    }


def compare_amendment(protocol_id: str, amendment_number: int) -> dict:
    """Compare an amendment against its base protocol version.

    Retrieves the amendment's current JSON and the base protocol version,
    then computes the diff.
    """
    amendment = get_amendment_detail(protocol_id, amendment_number)
    if not amendment:
        raise ValueError(f"Amendment {amendment_number} not found")

    base_version = amendment.get("base_version", "v0.1")
    base = get_version_detail(protocol_id, base_version)

    if not base:
        # Try to use the first version
        versions = _load_versions(protocol_id)
        base = versions[0] if versions else None

    if not base:
        raise ValueError(f"Base version not found for comparison")

    diff_sections = compute_diff(base["extracted_json"], amendment["extracted_json"])

    modified = [d for d in diff_sections if d["type"] in ("modified", "added")]
    substantive = [d for d in modified if d["severity"] == "substantive"]
    minor = [d for d in modified if d["severity"] == "minor"]

    return {
        "protocol_id": protocol_id,
        "amendment_number": amendment_number,
        "amendment_version": amendment["current_version"],
        "base_version": base_version,
        "summary": {
            "total_sections": len(diff_sections),
            "modified_count": len(modified),
            "substantive_count": len(substantive),
            "minor_count": len(minor),
        },
        "diff_sections": diff_sections,
        "changes_summary": amendment.get("changes_summary", []),
    }


# ============================================================================
# AUDIT LOG
# ============================================================================

def add_audit_entry(
    protocol_id: str,
    action: str,
    author: str = "System",
    details: dict = None,
):
    """Add an entry to the protocol's audit log."""
    entry = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "action": action,
        "author": author,
        "details": details or {},
        "protocol_id": protocol_id,
    }
    get_storage_backend().add_audit_entry(protocol_id, entry)
    return entry


def get_audit_log(protocol_id: str, limit: int = 50) -> List[dict]:
    """Get the audit log for a protocol."""
    return get_storage_backend().load_audit_log(protocol_id, limit)


# ============================================================================
# HELPERS
# ============================================================================

def _parse_version(version_str: str) -> tuple:
    """Parse 'v1.2' into (1, 2)."""
    v = version_str.lstrip("v")
    parts = v.split(".")
    try:
        return int(parts[0]), int(parts[1]) if len(parts) > 1 else 0
    except (ValueError, IndexError):
        return 0, 1


def _hash_json(data: dict) -> str:
    """Create a short content hash for change detection."""
    s = json.dumps(data, sort_keys=True, default=str)
    return hashlib.md5(s.encode()).hexdigest()[:12]


def _count_nonempty_fields(data: dict, depth: int = 0) -> int:
    """Count non-empty fields in a nested dict."""
    if depth > 10:
        return 0
    count = 0
    if isinstance(data, dict):
        for v in data.values():
            if isinstance(v, dict):
                count += _count_nonempty_fields(v, depth + 1)
            elif isinstance(v, list):
                count += len(v)
            elif v and str(v).strip() and str(v) not in ("None", "0", "[]", "{}"):
                count += 1
    return count


def _flatten_for_diff(data, prefix: str = "") -> dict:
    """Flatten a section to field-level key-value pairs for comparison."""
    result = {}
    if isinstance(data, dict):
        for k, v in data.items():
            key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                result.update(_flatten_for_diff(v, key))
            elif isinstance(v, list):
                result[key] = json.dumps(v, default=str)
            else:
                result[key] = str(v) if v is not None else ""
    elif isinstance(data, str):
        result[prefix] = data
    return result


def _summarize_section(section_data) -> str:
    """Create a brief text summary of a section for the diff display."""
    if isinstance(section_data, str):
        return section_data[:200]
    if isinstance(section_data, dict):
        parts = []
        for k, v in section_data.items():
            if v and str(v).strip() and str(v) not in ("None", "{}", "[]"):
                val = str(v)[:80]
                parts.append(f"{k}: {val}")
            if len(parts) >= 4:
                break
        return "; ".join(parts) if parts else "(empty section)"
    return str(section_data)[:200]


def _classify_severity(section_key: str, field_changes: list) -> str:
    """Classify change severity as 'substantive' or 'minor'.

    Substantive = changes that affect study design, animal counts, dosing,
    timelines, regulatory compliance, or cost.
    Minor = formatting, administrative, reporting adjustments.
    """
    substantive_sections = {
        "BasicDetails", "StudyInfo", "TestMaterial", "TestSystem",
        "ExperimentalDesign", "ExperimentalObservationsandProcedures",
        "LaboratoryAssessments", "TerminalProceduresandPathology",
        "RegulatoryCompliance", "Schedule",
    }

    substantive_fields = {
        "duration", "doselevels", "route", "species", "strain",
        "animals", "males", "females", "groups", "glp",
        "necropsy", "recovery", "sacrifice", "dose",
    }

    if section_key in substantive_sections:
        # Check if any field names relate to study-critical parameters
        for change in field_changes:
            field_lower = change["field"].lower()
            if any(sf in field_lower for sf in substantive_fields):
                return "substantive"
        # If 3+ fields changed in a substantive section, call it substantive
        if len(field_changes) >= 3:
            return "substantive"

    return "minor" if field_changes else "none"


def _describe_changes(section_key: str, field_changes: list) -> list:
    """Generate human-readable descriptions of field-level changes."""
    descriptions = []
    for change in field_changes[:8]:  # Cap at 8 descriptions
        field = change["field"].split(".")[-1]
        old = change["original"][:60] if change["original"] else "(empty)"
        new = change["amended"][:60] if change["amended"] else "(empty)"

        # Make human-friendly field name
        friendly = field.replace("_", " ").replace("And", " and ")
        # Add spaces before capitals (camelCase → sentence)
        import re
        friendly = re.sub(r'([a-z])([A-Z])', r'\1 \2', friendly)

        if not old or old == "(empty)":
            descriptions.append(f"{friendly} added: {new}")
        elif not new or new == "(empty)":
            descriptions.append(f"{friendly} removed (was: {old})")
        else:
            descriptions.append(f"{friendly} changed from \"{old}\" to \"{new}\"")

    if len(field_changes) > 8:
        descriptions.append(f"...and {len(field_changes) - 8} more field changes")

    return descriptions


def _assess_impact(section_key: str, field_changes: list) -> str:
    """Generate an impact assessment for the changed section."""
    impact_map = {
        "TestSystem": "Animal count or species changes may require IACUC amendment and updated cage space.",
        "ExperimentalDesign": "Study plan, dosing charts, and randomization tables may require updating.",
        "TerminalProceduresandPathology": "Pathology scheduling, slide preparation, and pathologist time may be affected.",
        "LaboratoryAssessments": "Additional sample collection and laboratory processing may be needed.",
        "TestMaterial": "Dose preparation and formulation analysis procedures may need revision.",
        "Schedule": "Study timeline adjustments may affect lab scheduling and resource allocation.",
        "RegulatoryCompliance": "Regulatory submission documents may require updating.",
        "Reporting": "Additional reporting milestones for project management.",
        "Personnel": "Personnel assignments may need to be updated.",
        "BasicDetails": "Core study parameters have changed; review all downstream documents.",
    }

    return impact_map.get(section_key, f"{len(field_changes)} field(s) modified in this section.")
